//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_APP_Setting> tbl_APP_Setting { get; set; }
        public virtual DbSet<tbl_OTHER_OPTIONS> tbl_OTHER_OPTIONS { get; set; }
        public virtual DbSet<tbl_OTHER_OPTIONS_Employee_Set> tbl_OTHER_OPTIONS_Employee_Set { get; set; }
        public virtual DbSet<tbl_OTHER_OPTIONS_FILTER> tbl_OTHER_OPTIONS_FILTER { get; set; }
        public virtual DbSet<tbl_OTHER_OPTIONS_ID_Set> tbl_OTHER_OPTIONS_ID_Set { get; set; }
        public virtual DbSet<tbl_OTHER_OPTIONS_SEARCH> tbl_OTHER_OPTIONS_SEARCH { get; set; }
        public virtual DbSet<tbl_prdcategory> tbl_prdcategory { get; set; }
        public virtual DbSet<tbl_useraccount> tbl_useraccount { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
        public virtual DbSet<tblStockType> tblStockTypes { get; set; }
        public virtual DbSet<tbl_exchangerates> tbl_exchangerates { get; set; }
        public virtual DbSet<tbl_customerorder> tbl_customerorder { get; set; }
        public virtual DbSet<tblStockTypeProduct> tblStockTypeProducts { get; set; }
        public virtual DbSet<tbl_suppliers> tbl_suppliers { get; set; }
        public virtual DbSet<tbl_products_Customers_Price> tbl_products_Customers_Price { get; set; }
        public virtual DbSet<tbl_mainstock> tbl_mainstock { get; set; }
        public virtual DbSet<tbl_orderdetails> tbl_orderdetails { get; set; }
        public virtual DbSet<tbl_products_Package> tbl_products_Package { get; set; }
        public virtual DbSet<tbl_products_Package_Detail> tbl_products_Package_Detail { get; set; }
        public virtual DbSet<tblOrderDetailsTemp> tblOrderDetailsTemps { get; set; }
        public virtual DbSet<tbl_App_Setting_Options> tbl_App_Setting_Options { get; set; }
        public virtual DbSet<tbl_BuyProducts> tbl_BuyProducts { get; set; }
        public virtual DbSet<tbl_products> tbl_products { get; set; }
        public virtual DbSet<tbl_mainstock_ordering> tbl_mainstock_ordering { get; set; }
        public virtual DbSet<tbl_customers> tbl_customers { get; set; }
        public virtual DbSet<tbl_customers_account_Cards_Type> tbl_customers_account_Cards_Type { get; set; }
        public virtual DbSet<tbl_customers_account_InOut_History> tbl_customers_account_InOut_History { get; set; }
        public virtual DbSet<tbl_customers_account> tbl_customers_account { get; set; }
    }
}
