//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderdetails
    {
        public string orderDetailsID { get; set; }
        public string customerOrderID { get; set; }
        public string prdID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string unitType { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> orderQty { get; set; }
        public Nullable<double> totalAmt { get; set; }
        public string PytStatus { get; set; }
        public string roomtableID { get; set; }
        public string ReservationID { get; set; }
        public Nullable<int> NumPrinted { get; set; }
        public Nullable<int> NumPrintedInv { get; set; }
        public Nullable<double> percDisc { get; set; }
        public Nullable<double> AmtDisc { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public Nullable<double> BuyingTotal { get; set; }
        public string userID { get; set; }
        public string TaxNote { get; set; }
        public string OrderDetailDescription { get; set; }
        public Nullable<double> Qty_for_Repaire { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Area_Size { get; set; }
        public string LOC_Location { get; set; }
        public string DMCode { get; set; }
        public string RPCode_Repaire { get; set; }
        public Nullable<double> NumHours { get; set; }
        public Nullable<double> Larbor_Cost { get; set; }
        public Nullable<double> Material_Cost { get; set; }
        public string PARKING_CardORBarcode { get; set; }
        public Nullable<System.DateTime> PARKING_DateIN { get; set; }
        public Nullable<System.DateTime> PARKING_DateOUT { get; set; }
        public string PARKING_Status { get; set; }
        public byte[] Photo1 { get; set; }
        public byte[] Photo2 { get; set; }
        public byte[] Photo3 { get; set; }
        public byte[] Photo4 { get; set; }
        public Nullable<double> orderQtyReturnTemp { get; set; }
        public Nullable<double> totalAmtReturnTemp { get; set; }
        public Nullable<double> orderQtyReturn { get; set; }
        public Nullable<double> totalAmtReturn { get; set; }
        public string statusReturn { get; set; }
        public Nullable<System.DateTime> dateReturn { get; set; }
        public Nullable<System.DateTime> dateExpire { get; set; }
        public Nullable<double> NumInCase { get; set; }
    }
}
