//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OTHER_OPTIONS_FILTER
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public string para_ReportName { get; set; }
        public string para_Stored_Pro_Name { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string RunID { get; set; }
        public Nullable<int> para_Calculate_Time { get; set; }
        public Nullable<int> paraEmployee_Set { get; set; }
        public Nullable<int> para01_cmdCalculate { get; set; }
        public Nullable<int> para02_cmdViewReportMS { get; set; }
        public Nullable<int> para03_cmdViewReportCR { get; set; }
        public Nullable<int> para04_cmdExport { get; set; }
        public Nullable<int> para05_cmdImport { get; set; }
        public string para06_cboGroup { get; set; }
        public string para07_cboName { get; set; }
        public Nullable<int> para08_0_TabMonthly { get; set; }
        public Nullable<System.DateTime> para08_1_cboMonthly { get; set; }
        public Nullable<System.DateTime> para08_2_Monthly_cboFrom { get; set; }
        public Nullable<System.DateTime> para08_3_Monthly_cboTo { get; set; }
        public Nullable<int> para09_0_TabDate { get; set; }
        public Nullable<System.DateTime> para09_1_Date { get; set; }
        public Nullable<int> para10_0_TabDate_From_To { get; set; }
        public Nullable<System.DateTime> para10_1_Date_From_To_cboFrom { get; set; }
        public Nullable<System.DateTime> para10_2_Date_From_To_cboTo { get; set; }
        public Nullable<int> para11_0_TabYearly { get; set; }
        public Nullable<System.DateTime> para11_1_Yearly_cboYear { get; set; }
        public string para_12_Note { get; set; }
        public string para_13_Note { get; set; }
        public string para_14_Note { get; set; }
        public string para_15_Note { get; set; }
        public string para_16_Note { get; set; }
        public string para_17_Note { get; set; }
        public string para_18_Note { get; set; }
        public string para_19_Note { get; set; }
        public string para_20_Note { get; set; }
        public string para_21_Note { get; set; }
        public string para_22_Note { get; set; }
        public string para_23_Note { get; set; }
        public string para_24_Note { get; set; }
        public string para_25_Note { get; set; }
        public Nullable<int> para_26_IS_Customers { get; set; }
        public Nullable<int> para_27_IS_PrdCategory { get; set; }
        public Nullable<int> para_28_IS_products { get; set; }
        public Nullable<int> para_29_IS_Sale { get; set; }
        public Nullable<int> para_30_IS_StockType { get; set; }
        public Nullable<int> para_31_IS_Suppliers { get; set; }
        public Nullable<int> para_32_IS_Useraccount { get; set; }
    }
}
