//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerorder
    {
        public string customerOrderID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string customerID { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<double> percentDiscount { get; set; }
        public Nullable<double> amtDiscount { get; set; }
        public Nullable<double> amtOrderExpend { get; set; }
        public Nullable<double> netAmount { get; set; }
        public Nullable<double> voidAmt { get; set; }
        public Nullable<double> Rate_VAT { get; set; }
        public Nullable<double> TotalForVAT { get; set; }
        public Nullable<double> VAT { get; set; }
        public string OUR_VAT_NO { get; set; }
        public Nullable<double> grandTotal { get; set; }
        public Nullable<double> amtReceived { get; set; }
        public Nullable<double> amtReturn { get; set; }
        public Nullable<double> amtOwed { get; set; }
        public string userID { get; set; }
        public Nullable<double> usdTokhr { get; set; }
        public Nullable<double> usdToTHB { get; set; }
        public string RandTID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string InvoiceNo { get; set; }
        public string voidStatus { get; set; }
        public string openingBalanceID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<double> usdTokhrChange { get; set; }
        public Nullable<bool> OwnerReceive { get; set; }
        public string SaleID { get; set; }
        public Nullable<double> TotalOwed { get; set; }
        public string DescripitonTerm { get; set; }
        public string Note { get; set; }
        public string PO { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipVia { get; set; }
        public string FOBPOINT { get; set; }
        public string ID_Ship { get; set; }
        public string CardTypeID { get; set; }
        public Nullable<double> CardTypeAmount { get; set; }
        public string TransportationInfo_Pkl_No { get; set; }
        public string TransportationInfo_No_Of_Pkg { get; set; }
        public string TransportationInfo_CTNR_No { get; set; }
        public string TransportationInfo_FDR { get; set; }
        public Nullable<System.DateTime> TransportationInfo_ETD_SIH { get; set; }
        public string TransportationInfo_Shipt { get; set; }
        public string TransportationInfo_GW { get; set; }
        public string TransportationInfo_8 { get; set; }
        public string TransportationInfo_9 { get; set; }
        public string TransportationInfo_10 { get; set; }
        public string TransportationInfo_11 { get; set; }
        public string TransportationInfo_12 { get; set; }
        public string TransportationInfo_13 { get; set; }
        public string TransportationInfo_14 { get; set; }
        public string TransportationInfo_15 { get; set; }
        public Nullable<double> RecieveUSD { get; set; }
        public Nullable<double> RecieveRiel { get; set; }
        public Nullable<double> OweUSD { get; set; }
        public Nullable<double> OweRiel { get; set; }
        public Nullable<double> ReturnUSD { get; set; }
        public Nullable<double> ReturnRiel { get; set; }
        public Nullable<double> AccountAMT { get; set; }
        public Nullable<double> AMT_Pay_By_MEMBER_Card { get; set; }
        public string ComputerName { get; set; }
        public Nullable<double> amtReturnToPayOldOwed { get; set; }
        public string DeliveryNo { get; set; }
        public string QuotationNo { get; set; }
        public Nullable<double> netAmountReturn { get; set; }
    }
}
