//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customers_account_InOut_History
    {
        public string CustAccInOutHistoryID { get; set; }
        public string CustomerAccountID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> RealMoney { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<double> BeginAmount { get; set; }
        public string customerOrderID { get; set; }
        public string UserID { get; set; }
        public string Username { get; set; }
        public string EditeNote { get; set; }
    }
}
