//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BuyProducts
    {
        public string BuyID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InvoiceNo { get; set; }
        public string SupplierID { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> PerDis { get; set; }
        public Nullable<double> AmtDis { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> AmtPay { get; set; }
        public Nullable<double> AmtLoan { get; set; }
        public string UserID { get; set; }
        public Nullable<double> usdtoKher { get; set; }
        public Nullable<double> usdtoTHB { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string StockID { get; set; }
        public string Description { get; set; }
    }
}
