//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_prdcategory
    {
        public string PrdCategID { get; set; }
        public string PrdCmpntID { get; set; }
        public string PrdCategory { get; set; }
        public string PrdCategoryKh { get; set; }
        public string PrdCategIDMain { get; set; }
        public Nullable<int> CategoryOrder { get; set; }
        public Nullable<double> MiniMumInstock { get; set; }
    }
}
