//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_App_Setting_Options
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> First { get; set; }
        public string Type { get; set; }
        public string PrinterName { get; set; }
    }
}
