//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_exchangerates
    {
        public string exchID { get; set; }
        public string currenciesFrm { get; set; }
        public string currenciesTo { get; set; }
        public Nullable<double> rates { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string Description { get; set; }
    }
}
