//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_suppliers
    {
        public string SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ContFirstName { get; set; }
        public string ContLastName { get; set; }
        public string JobTitle { get; set; }
        public string BusPhone { get; set; }
        public string MobilePhone { get; set; }
        public string FaxNumber { get; set; }
        public string Address { get; set; }
        public string ZipPostalCode { get; set; }
        public string Region { get; set; }
        public string supCity { get; set; }
        public string supCountry { get; set; }
        public string CompEmail { get; set; }
        public string WebPage { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> autoNo { get; set; }
    }
}
