//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mainstock
    {
        public string MainStockID { get; set; }
        public string ProductID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> StockinDate { get; set; }
        public string caseRetail { get; set; }
        public string unitType { get; set; }
        public Nullable<double> BuyingCost { get; set; }
        public Nullable<double> transCost { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> otherExp { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public string PytStatus { get; set; }
        public string CommentDetails { get; set; }
        public Nullable<System.DateTime> stockInDateTime { get; set; }
        public Nullable<double> qtyInStock { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string prdStatus { get; set; }
        public Nullable<double> usdTokhr { get; set; }
        public Nullable<double> usdTothb { get; set; }
        public string SupplierID { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string BuyID { get; set; }
        public string StockID { get; set; }
    }
}
