//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_APP_Setting
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public string Note { get; set; }
    }
}
