//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products_Package_Detail
    {
        public long Product_PackageDetail_ID { get; set; }
        public Nullable<long> Product_PackageID { get; set; }
        public string ProductID { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> SellingPriceUSD { get; set; }
        public string Description { get; set; }
    }
}
