//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mainstock_ordering
    {
        public string MainStockID { get; set; }
        public string ProductID { get; set; }
        public string unitType { get; set; }
        public Nullable<double> BuyingCost { get; set; }
        public Nullable<double> transCost { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string UserID { get; set; }
        public Nullable<double> SellingPriceUSD { get; set; }
        public string PrdNameEng { get; set; }
        public string barCode { get; set; }
        public string OrderComment { get; set; }
        public string PrdCategory { get; set; }
        public string BuyID { get; set; }
        public string BuyStatus { get; set; }
        public Nullable<System.DateTime> BuyReturnDate { get; set; }
    }
}
