//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_useraccount
    {
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isHome { get; set; }
        public Nullable<bool> isBackUp { get; set; }
        public Nullable<bool> isRestore { get; set; }
        public Nullable<bool> isFronDes { get; set; }
        public Nullable<bool> isStock { get; set; }
        public Nullable<bool> isSupplyer { get; set; }
        public Nullable<bool> isProduct { get; set; }
        public Nullable<bool> isExchange { get; set; }
        public Nullable<bool> isExpend { get; set; }
        public Nullable<bool> isUser { get; set; }
        public Nullable<bool> isReSalling { get; set; }
        public Nullable<bool> isReOldInvoice { get; set; }
        public Nullable<bool> isReTopSalling { get; set; }
        public Nullable<bool> isReVoidInvoice { get; set; }
        public Nullable<bool> isReStock { get; set; }
        public Nullable<bool> isReCustomer { get; set; }
        public Nullable<bool> isReSupplyer { get; set; }
        public Nullable<bool> isReUserActivity { get; set; }
        public Nullable<bool> isReMoney { get; set; }
        public Nullable<bool> isReCloseSalling { get; set; }
        public string StockID { get; set; }
        public string LangCode { get; set; }
    }
}
