//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public string ProductID { get; set; }
        public string PrdCategID { get; set; }
        public string SupplierID { get; set; }
        public string PrdNameEng { get; set; }
        public string PrdNameKh { get; set; }
        public string UnitType { get; set; }
        public Nullable<double> totalInStock { get; set; }
        public Nullable<double> minimalStock { get; set; }
        public Nullable<double> SellingPriceUSD { get; set; }
        public Nullable<double> SellingPriceKHR { get; set; }
        public Nullable<double> SellingPriceTHB { get; set; }
        public byte[] Photo { get; set; }
        public string Image { get; set; }
        public string OrderComment { get; set; }
        public string PrdDesc { get; set; }
        public string barCode { get; set; }
        public string Delstatus { get; set; }
        public Nullable<bool> isCutStock { get; set; }
        public string ProductIDRealStock { get; set; }
        public Nullable<double> NumInOne { get; set; }
        public Nullable<bool> IsUnique { get; set; }
        public string TaxNote { get; set; }
        public string Money_Sale_Type { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Area_Size { get; set; }
        public string LOC_Location { get; set; }
        public string DMCode { get; set; }
        public string RPCode_Repaire { get; set; }
        public Nullable<double> NumHours { get; set; }
        public Nullable<double> Larbor_Cost { get; set; }
        public Nullable<double> BuyingCost { get; set; }
        public Nullable<double> amtPercDisc { get; set; }
        public string amtDisc { get; set; }
    }
}
