//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customers_account
    {
        public string CustomerAccountID { get; set; }
        public string memberID { get; set; }
        public string AccountType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> RealMoneyRemain { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<double> LimitePay1Day { get; set; }
        public Nullable<double> LimitePay1Time { get; set; }
        public string Description { get; set; }
        public string EditeNote { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
