//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bill {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bill() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Resources.Bill", typeof(Bill).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amtDiscount.
        /// </summary>
        public static string amtDiscount {
            get {
                return ResourceManager.GetString("amtDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amtOwed.
        /// </summary>
        public static string amtOwed {
            get {
                return ResourceManager.GetString("amtOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amtReceived.
        /// </summary>
        public static string amtReceived {
            get {
                return ResourceManager.GetString("amtReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amtReturn.
        /// </summary>
        public static string amtReturn {
            get {
                return ResourceManager.GetString("amtReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustName.
        /// </summary>
        public static string CustName {
            get {
                return ResourceManager.GetString("CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandTotal.
        /// </summary>
        public static string grandTotal {
            get {
                return ResourceManager.GetString("grandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceNo.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderDate.
        /// </summary>
        public static string orderDate {
            get {
                return ResourceManager.GetString("orderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalAmount.
        /// </summary>
        public static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
