//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Resources.Payment", typeof(Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountType.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string AmtDisc {
            get {
                return ResourceManager.GetString("AmtDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmtOwed.
        /// </summary>
        public static string amtOwed {
            get {
                return ResourceManager.GetString("amtOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmtReceive.
        /// </summary>
        public static string amtReceived {
            get {
                return ResourceManager.GetString("amtReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmtReturn.
        /// </summary>
        public static string amtReturn {
            get {
                return ResourceManager.GetString("amtReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string custId {
            get {
                return ResourceManager.GetString("custId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customerOrderID {
            get {
                return ResourceManager.GetString("customerOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescripitonTerm {
            get {
                return ResourceManager.GetString("DescripitonTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit InvoiceNo.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetAmount.
        /// </summary>
        public static string netAmount {
            get {
                return ResourceManager.GetString("netAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmtReturn.
        /// </summary>
        public static string netAmountReturn {
            get {
                return ResourceManager.GetString("netAmountReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmtPayable.
        /// </summary>
        public static string PayableAmt {
            get {
                return ResourceManager.GetString("PayableAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnDate.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAmount.
        /// </summary>
        public static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAmount.
        /// </summary>
        public static string totalAmountTemp {
            get {
                return ResourceManager.GetString("totalAmountTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
