//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Product {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Product() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Resources.Product", typeof(Product).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string barCode {
            get {
                return ResourceManager.GetString("barCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyingCost.
        /// </summary>
        public static string BuyingCost {
            get {
                return ResourceManager.GetString("BuyingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubProduct.
        /// </summary>
        public static string ChildTitle {
            get {
                return ResourceManager.GetString("ChildTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImgUpload {
            get {
                return ResourceManager.GetString("ImgUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCutStock.
        /// </summary>
        public static string isCutStock {
            get {
                return ResourceManager.GetString("isCutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsUnique.
        /// </summary>
        public static string IsUnique {
            get {
                return ResourceManager.GetString("IsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinStock.
        /// </summary>
        public static string minimalStock {
            get {
                return ResourceManager.GetString("minimalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Money_Sale_Type {
            get {
                return ResourceManager.GetString("Money_Sale_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string NumInOne {
            get {
                return ResourceManager.GetString("NumInOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string OrderComment {
            get {
                return ResourceManager.GetString("OrderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string PrdCategory {
            get {
                return ResourceManager.GetString("PrdCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PrdDesc {
            get {
                return ResourceManager.GetString("PrdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PrdNameEng {
            get {
                return ResourceManager.GetString("PrdNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalePrice(Riel).
        /// </summary>
        public static string SellingPriceKHR {
            get {
                return ResourceManager.GetString("SellingPriceKHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalePrice.
        /// </summary>
        public static string SellingPriceUSD {
            get {
                return ResourceManager.GetString("SellingPriceUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WholesalePrice.
        /// </summary>
        public static string SellingPriceUSDForThisCus {
            get {
                return ResourceManager.GetString("SellingPriceUSDForThisCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string TaxNote {
            get {
                return ResourceManager.GetString("TaxNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InStock.
        /// </summary>
        public static string totalInStock {
            get {
                return ResourceManager.GetString("totalInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitType.
        /// </summary>
        public static string UnitType {
            get {
                return ResourceManager.GetString("UnitType", resourceCulture);
            }
        }
    }
}
